---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  dpi = 300
)
```

# `tna`: An R package for Transition Network Analysis

<!-- badges: start -->
<!-- badges: end -->


## Installation

You can install the development version of `tna` from [GitHub](https://github.com/) with:

```{r, eval = FALSE}
# install.packages("devtools")
devtools::install_github("sonsoleslp/tna")
```

## Example

Load the library
```{r}
library("tna")
```

Example data
```{r}
data("engagement", package = "tna")
```

Build a Markov model
```{r}
tna_model <- build_tna(engagement)
```

Plot the transition network
```{r tnaplot}
plot(tna_model)
```

Calculate the centrality measures
```{r}
cm <- centralities(tna_model, normalize = T)
cm
```

Plot the centrality measures
```{r centralitiesplot}
plot(cm, ncol =  4, scales = "fixed",
     line_color = tna_model$colors, point_color = tna_model$colors) 
```
Compare those who started as active with the rest
```{r}
tna_model_start_active <- build_tna(engagement[engagement[,1]=="Active",])
tna_model_start_other <- build_tna(engagement[engagement[,1]!="Active",])
plot_compare(tna_model_start_active, tna_model_start_other)
```

