---
title: "Full example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Full example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 10,
  fig.height = 6,
  out.width = "100%",
  dpi = 300,
  comment = "#>"
)
```

```{r, warning = F,  message = FALSE, results = FALSE }
library("tna")
library("tibble")
library("dplyr")
library("gt")
```

Import the data
```{r}
data("engagement", package = "tna")
```

Build the model
```{r}
tna_model <- tna(engagement)
```

Plot the model
```{r}
plot(tna_model)
```

Initial probabilities
```{r}
data.frame(`Initial prob.` = tna_model$inits, check.names = FALSE) |> 
  rownames_to_column("Engagement state") |> 
  arrange(desc(`Initial prob.`)) |> 
  gt() |> 
  fmt_percent()
```

Transition probabilities
```{r}
tna_model$weights |> 
  data.frame() |> 
  rownames_to_column("From\\To") |> 
  gt() |>
  fmt_percent()
```

Centrality measures
```{r}
centrality_measures <- c("BetweennessRSP", "Closeness", "InStrength", "OutStrength")
cents_withoutloops <- centralities(
  tna_model, 
  measures = centrality_measures, 
  loops = FALSE, 
  normalize = TRUE
)
plot(cents_withoutloops, ncol = 2, model = tna_model)
```
